version: '3.8'

services:
  orchestrator:
    image: nas.fooguru.org:30095/valkyrie-orchestrator:latest
    container_name: valkyrie-orchestrator
    restart: unless-stopped
    ports:
      - "4000:4000"
    env_file:
      - .env
    volumes:
      - valkyrie-generated-data:/app/generated

  web:
    image: nas.fooguru.org:30095/valkyrie-web:latest
    container_name: valkyrie-web
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - PORT=3000

volumes:
  valkyrie-generated-data:
